[[redirects]]
  from = "/"
  to = "/login"
  status = 301
  force = true

[build]
  base = "./"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
